bboard/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

from .views import *

app_name = 'bboard'

urlpatterns = [
    path('<int:rubric_id>/',    BbByRubricView.as_view(),   name='by_rubric'),  # имя маршрута by_rubric
    path('',                    index,                      name='index'),      # имя маршрута index
    path('add/',                BbCreateView.as_view(),     name='add'),     # добавление записи
    path('edit/<int:pk>/',      BbUpdateView.as_view(),     name='edit'),    # изменение записи
    path('delete/<int:pk>/',    BbDeleteView.as_view(),     name='delete'),  # удаление записи
    path('detail/<int:pk>/',    BbDetailView.as_view(),     name='detail'),  # просмотр записи

    path('accounts/login/',     LoginView.as_view(),        name='login'),   # логин
    path('accounts/logout/',    LogoutView.as_view(),       name='logout'),  # выход из под пользователя

    path('accounts/password_change/',       PasswordChangeView.as_view(      # изменение пароля
        template_name='registration/change_password.html', success_url=reverse_lazy('bboard:password_change_done')),
        name='password_change'),
    path('accounts/password_change/done/',  PasswordChangeDoneView.as_view(  # сообщение об успешном изменении пароля
        template_name='registration/password_changed.html'), name='password_change_done'),

    path('accounts/password_reset/', PasswordResetView.as_view(              # запрос на сброс пароля
        template_name='registration/reset_password.html',
        success_url=reverse_lazy('bboard:password_reset_done'),
        subject_template_name='registration/reset_subject.txt',
        email_template_name='registration/reset_email.txt'),
        name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(template_name='registration/email_sent.html'),
         name='password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view( # сброс пароля
        template_name='registration/confirm_password.html', success_url=reverse_lazy('bboard:password_reset_complete')
    ), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(
        template_name='registration/password_confirmed.html'), name='password_reset_complete'),


    path('pictures/', add_picture, name='add_picture'),


    # REST

    path('api/rubrics/', api_rubrics, name='apirub'),
    path('api/bboard/<int:pk>/', BboardDetailRestView.as_view(), name='apirub'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bboard.urls', namespace='')),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bboard/models.py
from django.db import models
from datetime import datetime
from os.path import splitext

# Create your models here.


class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['name']

    def __str__(self):
        """строковое представление модели"""
        return self.name


class Bb(models.Model):
    title = models.CharField(max_length=50, verbose_name='Товар')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')
    price = models.FloatField(null=True, blank=True, verbose_name='Цена')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
    rubric = models.ForeignKey('Rubric', null=True, on_delete=models.PROTECT, verbose_name='Рубрика')

    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-published']

    def __str__(self):
        """строковое представление модели"""
        return self.title


def get_timestamp_path(instance, filename):
    return '%s%s' % (datetime.now().timestamp(), splitext(filename)[1])


class Img(models.Model):

    img = models.ImageField(verbose_name='Изображение', upload_to=get_timestamp_path)
    desc = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

    def delete(self, *args, **kwargs):
        self.img.delete(save=False)             # Удаление файла при удалении записи
        super().delete(*args, **kwargs)

bboard/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from .models import *
from django import forms
from captcha.fields import CaptchaField
from django.core import validators


class BbForm(ModelForm):
    price = forms.DecimalField(decimal_places=2)
    captcha = CaptchaField(label='Введите текст с картинки', error_messages={'invalid': 'Неправильный текст капчи'})

    class Meta:
        model = Bb
        fields = ('title', 'content', 'price', 'rubric', 'captcha')

    def clean(self):
        super().clean()
        errors = {}
        if not self.cleaned_data['content']:
            errors['content'] = ValidationError('Укажите описание продаваемого товара')
        if not self.cleaned_data['price']:
            errors['price'] = ValidationError('Укажите правильное значение цены')
        elif int(self.cleaned_data['price']) < 0:
            errors['price'] = ValidationError('Укажите неотрицательное значение цены')
        if errors:
            raise ValidationError(errors)


class SearchFrom(forms.Form):
    keyword = forms.CharField(max_length=20, label='Искомое слово')
    rubric = forms.ModelChoiceField(queryset=Rubric.objects.all(), label='Рубрика')


class ImgForm(forms.ModelForm):
    img = forms.ImageField(label='Изображение', validators=[validators.FileExtensionValidator(
        allowed_extensions=('gif', 'jpg', 'png', 'jpeg'))],
        error_messages={'invalid_extension': 'Этот формат файлов не поддерживается'},
        widget=forms.widgets.ClearableFileInput(attrs={'multiple':True}))
    desc = forms.CharField(label='Описание', widget=forms.widgets.Textarea())

    class Meta:
        model = Img
        fields = '__all__'

bboard/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator
from django.template.response import TemplateResponse
from django.contrib.messages.views import SuccessMessageMixin
from rest_framework.views import APIView

from .forms import *

from .models import *
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.decorators.http import require_http_methods

#  REST

from django.http import JsonResponse
from .serializer import *
from rest_framework.response import Response
from rest_framework.decorators import api_view


# Create your views here.


def index(request):
    """Контроллер главной страницы"""
    imgs = Img.objects.all()
    bbs = Bb.objects.all()
    paginator = Paginator(bbs, 5)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)

    page_start = 1

    if int(page_num) > 2:
        page_start = int(page_num) - 2

    if int(page_num) + 2 >= page.paginator.num_pages:
        page_end = page.paginator.num_pages
    else:
        page_end = int(page_num) + 3

    page_list = list(range(int(page_start), page_end + 1))

    context = {'page': page, 'bbs': page.object_list, 'page_list': page_list, 'imgs': imgs}
    return TemplateResponse(request, 'bboard/index.html', context)


class BbCreateView(SuccessMessageMixin, CreateView):
    """Контроллер создания объявления"""
    template_name = 'bboard/create.html'  # путь к файлу шаблона для вывода страницы с формой
    form_class = BbForm  # класс формы
    success_url = '/{rubric_id}'  # адрес для перехода в случае успеха через имя маршрута
    success_message = 'Объявление создано'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class BbUpdateView(SuccessMessageMixin, UpdateView):
    """Контроллер изменения объявления"""
    model = Bb
    form_class = BbForm  # класс формы
    success_url = '/'  # адрес для перехода в случае успеха через имя маршрута
    success_message = 'Объявление изменено'
    template_name_suffix = '_update'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['rubrics'] = Rubric.objects.all()
        return context


class BbDeleteView(SuccessMessageMixin, DeleteView):
    """Контроллер удаления объявления с подтверждением"""
    model = Bb
    success_url = '/'
    success_message = 'Объявление удалено'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context


class BbDetailView(DetailView):
    """Контроллер подробного вывода одной записи"""
    model = Bb

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context


class BbByRubricView(LoginRequiredMixin, ListView):
    """Контроллер вывода всех записей по рубрике"""
    template_name = 'bboard/by_rubric.html'
    context_object_name = 'bbs'

    # def get_paginator(self, queryset, per_page, orphans=0,
    #                   allow_empty_first_page=True, **kwargs):
    #     return Paginator(Rubric.objects.get(pk=self.kwargs['rubric_id']), 5)

    def get_queryset(self):
        return Bb.objects.filter(rubric=self.kwargs['rubric_id'])

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['current_rubric'] = Rubric.objects.get(pk=self.kwargs['rubric_id'])
        return context


def add_picture(request):
    if request.method == 'POST':
        form = ImgForm(request.POST, request.FILES)
        if form.is_valid():
            for file in request.FILES.getlist('img'):
                img = Img()
                img.desc = form.cleaned_data['desc']
                img.img = file
                img.save()
            return redirect('bboard:index')
    else:
        form = ImgForm()
    context = {'form': form}
    return render(request, 'bboard/upload_picture.html', context)


# REST

@api_view(['GET'])
def api_rubrics(request):
    if request.method == 'GET':
        rubrics = Rubric.objects.filter(id=1)
        serializer = RubricSerializer(rubrics, many=True)
        return Response(data=serializer.data, template_name=None)


class BboardDetailRestView(APIView):

    def get(self, request, pk):
        bb = Bb.objects.get(id=pk)
        serializer = BboardSerialiser(bb, many=False)
        return Response(serializer.data)


# def add_and_save(request):
#     rubrics = Rubric.objects.all()
#     if request.method == 'POST':
#         bbf = BbForm(request.POST)
#         if bbf.is_valid():
#             bbf.save()
#             return redirect('bboard:by_rubric', rubric_id=bbf.cleaned_data['rubric'].pk)
#         else:
#             context = {'form': bbf, 'rubrics': rubrics}
#             return render(request, 'bboard/create.html', context)
#     else:
#         bbf = BbForm()
#         context = {'form': bbf, 'rubrics': rubrics}
#         return render(request, 'bboard/create.html', context)


# def by_rubric(request, rubric_id):
#    bbs = Bb.objects.filter(rubric=rubric_id)
#    rubrics = Rubric.objects.all()
#    current_rubric = Rubric.objects.get(pk=rubric_id)
#    context = {'bbs': bbs, 'rubrics': rubrics, 'current_rubric': current_rubric}
#    return render(request, 'bboard/by_rubric.html', context)


# class BbCreateView(FormView):
#     """контроллер для создания объявления"""
#     template_name = 'bboard/create.html'
#     form_class = BbForm
#     initial = {'price': 0.0}
#
#     def get_context_data(self, *args, **kwargs):
#         context = super().get_context_data(*args, **kwargs)
#         context['rubrics'] = Rubric.objects.all()
#         return context
#
#     def form_valid(self, form):
#         form.save()
#         return super().form_valid(form)
#
#     def get_form(self, form_class=None):
#         self.object = super().get_form(form_class)
#         return self.object
#
#     def get_success_url(self):
#         return reverse('bboard:by_rubric', kwargs={'rubric_id': self.object.cleaned_data['rubric'].pk})

bboard/templates/bboard/bb_confirm_delete.html
{% extends "layout/basic.html" %}

{% block title %}Удаление объявления{% endblock %}

{% block content %}

<h2>Удаление объявления</h2>
<p>Рубрика: {{ bb.rubric.name }}</p>
<p>Товар: {{ bb.title }}</p>
<p>{{ bb.content }}</p>
<p>Цена: {{ bb.price }}</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
</form>
{% endblock content%}

bboard/templates/bboard/bb_detail.html
{% extends "layout/basic.html" %}

{% block title %}{{ bb.title }}{% endblock %}

{% block content %}
<p>Рубрика: {{ bb.rubric.name }}</p>
<h2>{{ bb.title }}</h2>
<p>{{ bb.content }}</p>
<p>{{ bb.price }}</p>
{% endblock content%}

bboard/templates/bboard/bb_update.html
{% extends "layout/basic.html" %}

{% block title %}Изменение объявления{% endblock %}

{% block content %}
<h2>Изменение объявления</h2>
<form action="{% url 'bboard:edit' pk=bb.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Изменить">
</form>
{% endblock content%}

bboard/templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}
<h2>Рубрика: {{ current_rubric.name }}</h2>
{% for bb in bbs %}
<div>
    <h2><a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
    <p>{{ bb.content }}</p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    <p><a href="{% url 'bboard:edit' pk=bb.pk %}">Изменить</a> - <a href="{% url 'bboard:delete' pk=bb.pk %}">Удалить</a></p>
</div>
{% endfor %}
{% endblock content %}

bboard/templates/bboard/create.html
{% extends "layout/basic.html" %}

{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>
<form  action="{% url 'bboard:add' %}" method="post">
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
        {{hidden}}
    {% endfor %}

    {% if form.non_field_errors %}
    <ul>
        {% for error in form.non_field_errors %}
        <li><em>{{error|escape}}</em></li>
        {% endfor %}
    </ul>
    {% endif %}

    {% for field in form.visible_fields %}
        {% if field.errors %}
            <ul>
            {% for error in field.errors %}
                <li><em>{{ error|escape }}</em></li>
            {% endfor %}
            </ul>
        {% endif %}
    <p>{{ field.label_tag }} <br> {{ field }} <br> {{field.help_text }}</p>
    {% endfor %}
    <p><input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Добавить"></p>
</form>
{% endblock content %}

bboard/templates/bboard/index.html
{% extends "layout/basic.html" %}

{% load thumbnail %}

{% block content %}
{% for bb in bbs %}
<div>
    <h2><a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
    <p>{{ bb.content }} </p>
    <p>{{ bb.published|date:"d.m.Y h:i:s" }}</p>
    <p><a href="{% url 'bboard:edit' pk=bb.pk %}">Изменить</a> - <a href="{% url 'bboard:delete' pk=bb.pk %}">Удалить</a></p>
</div>
{% endfor %}

<div>
    <ui class="pagination">
        {% if page.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">&laquo;</a></li>
        {% endif %}
        {% for page_num in page_list %}
            {% if page_num == page.number %}
                <li class="page-item active"> <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a> </li>
            {% else %}
                <li class="page-item"> <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a> </li>
            {% endif %}
        {% endfor %}
        {% if page.has_next %}
            <a class="page-link" href="?page={{ page.next_page_number }}">&raquo;</a>
        {% endif %}
    </ui>
</div>

{% for img in imgs %}
<div>
    <div class="modal fade" id="id{{ img.id }}" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered " role="document">
        <!--Content-->
            <div class="modal-content">
                <!--Body-->
                <div class="modal-body">
                    <div>
                        <img src="{{ img.img.url }}" class="modal-body col-sm" >
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<a><img class="img-fluid z-depth-1" src="{% thumbnail img.img 'default' %}"
        data-toggle="modal" data-target="#id{{ img.id }}"></a>
{% endfor %}

{% endblock content%}

bboard/templates/bboard/upload_picture.html
{% extends "layout/basic.html" %}
{% block title %}Добавление объявления{% endblock %}
{% block content %}

<form enctype="multipart/form-data" action="{% url 'bboard:add_picture' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Добавить">
</form>

{% endblock content %}